### ISSUE TITLE
Isn't working with Adidas.de

### ISSUE THREAD

**Issue by T3RRORTOAST** [bopped/Adidas-Wishlist#1]
I don't know why, but its not working with adidas.de could you take a look into that?

**Comment by bopped** [comment]
Just tried it. It is working. 
<img width="1334" alt="screen shot 2017-11-06 at 7 47 44 pm" src="https://user-images.githubusercontent.com/22569645/32471452-60040d5c-c32b-11e7-974a-9ebcae95f3d3.png">
